# -*- coding: utf-8 -*-
"""Test 100

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18R8ho3fZ2gEXvQ_vYXte0dUjLxa1YYmQ
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
import matplotlib.lines as mlines
import warnings, os, time, json

warnings.filterwarnings('ignore')
np.random.seed(2024)

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Dataset")
OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "outputs", "100_requests")
os.makedirs(OUT_DIR, exist_ok=True)

VEH_COLORS = [
    '#E63946','#457B9D','#2A9D8F','#F4A261','#8338EC',
    '#06D6A0','#FB5607','#3A86FF','#FF006E','#FFBE0B'
]


# ══════════════════════════════════════════════════════════════════════════════
#  1.  DATA LOADER
# ══════════════════════════════════════════════════════════════════════════════

class DataLoader:
    """Loads, validates and pre-computes all dataset quantities."""

    def __init__(self, req_file: str = "requests_.csv"):
        up = DATA_DIR
        self.nodes    = pd.read_csv(f"{up}/nodes.csv")
        self.requests = pd.read_csv(f"{up}/{req_file}")
        self.vehicles = pd.read_csv(f"{up}/vehicles.csv")
        self.stations = pd.read_csv(f"{up}/charging_stations.csv")
        self.prices   = pd.read_csv(f"{up}/price_schedule.csv")
        self.params_df= pd.read_csv(f"{up}/parameters.csv")

        # Distance matrix (N×N km)
        dm_raw        = pd.read_csv(f"{up}/distance_matrix.csv", index_col=0)
        self.dist_mat = dm_raw.values.astype(np.float64)
        self.N        = self.dist_mat.shape[0]   # 602

        P = dict(zip(self.params_df['parameter'],
                     self.params_df['value'].astype(float)))

        # Battery parameters (Section I of formulation)
        self.B_max  = P['battery_capacity_kWh']          # 30 kWh
        self.kappa  = float(self.vehicles[
                            'max_energy_consumption_kWh_per_km'].iloc[0])
        self.eta    = P['charging_efficiency']            # 0.90
        self.B_min  = 0.10 * self.B_max                  # 3 kWh (10% floor)
        self.B_thr  = 0.35 * self.B_max                  # 10.5 kWh charge trigger

        # Counts
        self.n_req  = len(self.requests)
        self.n_veh  = len(self.vehicles)
        self.n_stat = len(self.stations)                  # 602

        # Charging levels from model_config.json: {0, 5, 15, 20} kWh
        self.charge_levels = np.array([0.0, 5.0, 15.0, 20.0])
        self.c_max         = 20.0                        # max per visit

        # Price per station: rescaled to paper's stated [0.50, 1.00] $/kWh
        peak_mult = float(self.prices['price_multiplier'].max())
        raw_p     = self.stations['base_price_per_kWh'].values * peak_mult
        lo, hi    = raw_p.min(), raw_p.max()
        self.node_price = (0.50 + (raw_p - lo) / (hi - lo + 1e-9) * 0.50
                           ).astype(float)               # (N,)

        # Station capacity: large_allowable × n_veh (per-station ceiling)
        self.C_max_s = (self.stations['large_allowable_kWh'].values
                        * self.n_veh).astype(float)      # (N,)

        # Node coordinates (for plotting)
        self.xy = self.nodes[['x_km', 'y_km']].values   # (N,2)

        # Request arrays
        self.req_pickup   = self.requests['pickup_node_id'].values    # (R,)
        self.req_delivery = self.requests['delivery_node_id'].values  # (R,)
        self.req_priority = self.requests['service_priority'].values.astype(float)

        # Depot
        self.start = int(self.vehicles['start_node_id'].iloc[0])  # 0
        self.end   = int(self.vehicles['end_node_id'].iloc[0])    # 1

        # Pre-computed: direct trip energy per request (used in gradients)
        dm = self.dist_mat
        p  = self.req_pickup;  d = self.req_delivery
        self.trip_km     = dm[self.start, p] + dm[p, d] + dm[d, self.end]
        self.trip_energy = self.trip_km * self.kappa

        self._print_summary()

    def _print_summary(self):
        avg_load = self.trip_energy.mean() * self.n_req / self.n_veh
        print(f"[Data]  N={self.N}  R={self.n_req}  K={self.n_veh}  S={self.n_stat}")
        print(f"        B_max={self.B_max:.0f} kWh  κ={self.kappa:.6f} kWh/km  "
              f"η={self.eta:.2f}  B_min={self.B_min:.1f} kWh  B_thr={self.B_thr:.1f} kWh")
        print(f"        Price: ${self.node_price.min():.3f}–"
              f"${self.node_price.max():.3f}/kWh")
        print(f"        Trip energy: {self.trip_energy.min():.2f}–"
              f"{self.trip_energy.max():.2f} kWh  "
              f"avg load/vehicle={avg_load:.2f} kWh "
              f"({'NEEDS CHARGING' if avg_load>self.B_max-self.B_min else 'feasible without charging'})")


# ══════════════════════════════════════════════════════════════════════════════
#  2.  VEHICLE AGENT
# ══════════════════════════════════════════════════════════════════════════════

class VehicleAgent:
    """
    Vehicle subproblem agent  (Section V of formulation).

    Decision variables:
      y^k ∈ [0,1]^R    continuous assignment weights  (M1)
      c^k ∈ [0,20]^N   continuous charging amounts    (M5)

    Key charging update [Eq. C]  (M4):
      c_feas_s  = min charge at s to keep SOC ≥ B_min  (mandatory)
      c_price_s = max(0, w_s − (π_s + μ_s)/ρ)          (price-optimal)
      c_s^k     = max(c_feas_s, c_price_s)

    Charging is computed AFTER routing, not before  (fixes update-order bug).

    Route:  greedy NN with pickup→delivery precedence  (M9)
    Price optimisation:  greedy look-back pre-charging  (M6)
    """

    def __init__(self, kid: int, data: DataLoader):
        self.kid  = kid
        self.data = data
        K, R, N   = data.n_veh, data.n_req, data.N

        self.B_init = float(data.vehicles.iloc[kid]['initial_battery_kWh'])

        # ── Decision variables ────────────────────────────────────────────
        self.y = self._sector_init(kid, K, R)   # (R,) in [0,1]
        self.c = np.zeros(N)                    # (N,) in [0, c_max]

        # ── Dual variables (broadcast by ConsensusAgent) ──────────────────
        self.lam = np.zeros(R)           # λ_r^k
        self.mu  = np.zeros(N)           # μ_s^k
        self.z   = np.full(R, 1.0 / K)  # z_r^k (consensus copy)
        self.w   = np.zeros(N)           # w_s^k (consensus copy)

        # ── Result storage ────────────────────────────────────────────────
        self.route         = [data.start, data.end]
        self.soc_profile   = [self.B_init, self.B_init]
        self.charge_events = []   # list of (node, kWh, soc_before, soc_after)

    # ── Sector initialisation (M3) ────────────────────────────────────────
    def _sector_init(self, kid, K, R) -> np.ndarray:
        """Initialise y^k with angular-sector affinity to break symmetry (M3)."""
        d    = self.data
        dxy  = d.xy[d.start]
        pxy  = d.xy[d.req_pickup]
        dist = np.linalg.norm(pxy - dxy, axis=1) + 1e-6
        ang  = np.arctan2(pxy[:,1]-dxy[1], pxy[:,0]-dxy[0])
        sec  = 2.0 * np.pi * kid / K
        aff  = (1.0/dist) * np.clip(1.0 + 0.85*np.cos(ang-sec), 0.05, 2.0)
        y    = aff / (aff.sum()+1e-9) * (R / K)
        return np.clip(y, 0.0, 1.0)

    # ── Main subproblem solve ─────────────────────────────────────────────
    def solve(self, rho: float):
        """
        One ADMM vehicle-subproblem update.

        Order of operations:
          1. Update y via proximal gradient (closed-form)
          2. Build greedy NN route from current y
          3. Compute c_feas from actual route SOC simulation
          4. Update c = max(c_feas, c_price)  [Eq. C]
          5. Final SOC simulation with c for reporting
        """
        # Step 1: y update
        self._update_y(rho)

        # Step 2: build route
        route = self._build_greedy_route()

        # Step 3: c_feas from route simulation
        c_feas = self._compute_c_feas(route)

        # Step 4: c = max(c_feas, c_price)  [Eq. C, M4]
        c_price = np.maximum(0.0,
                             self.w - (self.data.node_price + self.mu)
                             / (rho + 1e-8))
        c_price = np.clip(c_price, 0.0, self.data.c_max)
        self.c  = np.maximum(c_feas, c_price)

        # Step 5: simulate final SOC (sets self.route, self.soc_profile,
        #          self.charge_events)
        self._simulate_soc(route)

    # ── Step 1: y update ─────────────────────────────────────────────────
    def _update_y(self, rho: float):
        """
        Proximal gradient on assignment variable y^k.

        grad = α·cost_r/normalise + λ_r + ρ(y_r − z_r)

        Load-balance gradient deliberately omitted (M2):
        it causes ‖Y−Z‖ → √3 deadlock diagnosed analytically.
        """
        g_route = 1.0 * self.data.trip_km / 200.0          # (R,) normalised
        g_admm  = self.lam + rho * (self.y - self.z)        # (R,)
        step    = 1.0 / (rho + 1.0 + 1e-8)
        self.y  = np.clip(self.y - step * (g_route + g_admm), 0.0, 1.0)

    # ── Step 2: greedy NN route ───────────────────────────────────────────
    def _build_greedy_route(self) -> list:
        """
        Greedy nearest-neighbour pickup-delivery tour (M9).
        Select top ⌈R/K⌉+2 requests by y-score; enforce pickup→delivery (M7).
        Returns list of node IDs.
        """
        d       = self.data
        dm      = d.dist_mat
        K       = d.n_veh
        R_cap   = int(np.ceil(d.n_req / K)) + 2             # (M7)
        score   = self.y * (1.0 + 0.03 * d.req_priority)
        order   = np.argsort(-score)
        thresh  = max(0.10, 0.15 / K)

        assigned = []
        for r in order:
            if self.y[r] >= thresh:
                assigned.append(r)
                if len(assigned) >= R_cap:
                    break
        if not assigned:
            assigned = [order[0]]

        pend_p  = set(assigned)
        pend_d  = {}
        route   = [d.start]
        current = d.start

        for _ in range(4 * len(assigned) + 4):
            if not pend_p and not pend_d:
                break
            best = None; best_dist = np.inf; btype = None; br = None
            for r in pend_p:
                n = int(d.req_pickup[r]);   dist = dm[current, n]
                if dist < best_dist:
                    best_dist, best, btype, br = dist, n, 'P', r
            for r in pend_d:
                n = int(d.req_delivery[r]); dist = dm[current, n]
                if dist < best_dist:
                    best_dist, best, btype, br = dist, n, 'D', r
            if best is None:
                break
            route.append(best)
            if btype == 'P':
                pend_p.discard(br); pend_d[br] = best
            else:
                pend_d.pop(br, None)
            current = best

        route.append(d.end)
        return route

    # ── Step 3: c_feas from SOC simulation ───────────────────────────────
    def _compute_c_feas(self, route: list) -> np.ndarray:
        """
        Compute minimum feasibility charging (M4).

        Simulate SOC along route with NO charging.
        Whenever SOC < B_thr (35% B_max), charge at that node to 80% B_max.
        Price-aware look-back (M6): if a cheaper earlier node exists on the
        route AND pre-charging there would prevent this stop, use the earlier
        cheaper station instead.

        Returns c_feas: sparse array (N,) with needed kWh at each node.
        """
        d      = self.data
        dm     = d.dist_mat
        c_feas = np.zeros(d.N)
        soc    = self.B_init

        # Forward pass: identify where charging is needed
        needs = []   # (route_idx, soc_at_arrival, needed_kWh)
        soc_at = [self.B_init]
        for i in range(1, len(route)):
            energy = d.kappa * dm[route[i-1], route[i]]
            soc    = max(d.B_min, soc - energy)
            soc_at.append(soc)
            if soc < d.B_thr:
                target  = 0.80 * d.B_max
                needed  = max(0.0, (target - soc) / d.eta)
                needed  = min(needed, d.c_max)
                needs.append((i, soc, needed, route[i]))
                soc     = min(d.B_max, soc + d.eta * needed)

        if not needs:
            return c_feas                                   # no charging needed

        # Price-aware look-back (M6):
        # For each charging stop at node hi_node (price pi_hi),
        # check if charging earlier at lo_node (price pi_lo < pi_hi)
        # avoids the hi_node stop entirely.
        assigned_charge = {}   # route_idx → kWh
        for (i, soc_arr, needed, hi_node) in needs:
            pi_hi = d.node_price[hi_node]
            best_idx  = i
            best_price= pi_hi

            # Look back at candidate earlier stations on route
            for j in range(max(0, i-6), i):
                lo_node = route[j]
                if lo_node >= d.n_stat:
                    continue
                pi_lo = d.node_price[lo_node]
                if pi_lo >= best_price - 0.05:       # significant saving needed
                    continue
                # Check if pre-charging at j removes the need at i
                soc_after_pre = min(d.B_max,
                                    soc_at[j] + d.eta * needed)
                # Re-simulate soc from j to i with pre-charging
                soc_sim = soc_after_pre
                feasible = True
                for k in range(j+1, i+1):
                    e = d.kappa * dm[route[k-1], route[k]]
                    soc_sim = soc_sim - e
                    if soc_sim < d.B_min:
                        feasible = False; break
                if feasible and soc_sim >= d.B_thr:
                    best_idx   = j
                    best_price = pi_lo

            # Assign the needed charge to the chosen station
            if best_idx not in assigned_charge:
                assigned_charge[best_idx] = 0.0
            assigned_charge[best_idx] += needed

        # Write to c_feas array
        for idx, kwh in assigned_charge.items():
            node = route[idx]
            c_feas[node] = min(kwh, d.c_max)

        return c_feas

    # ── Step 5: simulate SOC with actual c ───────────────────────────────
    def _simulate_soc(self, route: list):
        """Run final SOC simulation with self.c; record charge_events."""
        d          = self.data
        dm         = d.dist_mat
        soc        = self.B_init
        soc_pr     = [soc]
        ch_ev      = []
        current    = route[0]

        for i in range(1, len(route)):
            node   = route[i]
            energy = d.kappa * dm[current, node]
            soc    = max(d.B_min, soc - energy)

            # Charge at this node if c[node] > 0
            amt = float(self.c[node])
            if amt > 0.01:
                amt    = min(amt, d.c_max, (d.B_max - soc) / d.eta)
                if amt > 0.01:
                    soc_b  = soc
                    soc    = min(d.B_max, soc + d.eta * amt)
                    ch_ev.append((node, amt, soc_b, soc))

            soc_pr.append(soc)
            current = node

        self.route         = route
        self.soc_profile   = soc_pr
        self.charge_events = ch_ev

    # ── Cost helpers ──────────────────────────────────────────────────────
    def route_cost(self) -> float:
        dm = self.data.dist_mat
        return float(sum(dm[self.route[i], self.route[i+1]]
                         for i in range(len(self.route)-1)))

    def charging_cost(self) -> float:
        return float(sum(self.data.node_price[n] * amt
                         for n, amt, _, _ in self.charge_events))

    def final_soc(self) -> float:
        return float(self.soc_profile[-1]) if self.soc_profile else self.B_init

    def min_soc(self) -> float:
        return float(min(self.soc_profile)) if self.soc_profile else self.B_init


# ══════════════════════════════════════════════════════════════════════════════
#  3.  CHARGING STATION AGENT
# ══════════════════════════════════════════════════════════════════════════════

class ChargingStationAgent:
    """
    Station subproblem  (Section VI of formulation).

    min_{c_s^k ≥ 0}  π_s · Σ_k c_s^k
                     + Σ_k [ μ_s^k(c_s^k − w_s^k) + (ρ/2)(c_s^k−w_s^k)² ]
    s.t.  Σ_k c_s^k ≤ Ĉ_s

    Closed-form:  c_s^{k*} = max(0, w_s^k − (π_s + μ_s^k)/ρ)
    Followed by proportional capacity projection if Σ_k c_s^{k*} > Ĉ_s.
    """

    def __init__(self, sid: int, data: DataLoader):
        self.sid   = sid
        self.pi    = float(data.node_price[sid])
        self.C_max = float(data.C_max_s[sid])
        self.c_max = data.c_max
        K          = data.n_veh
        self.c     = np.zeros(K)
        self.mu    = np.zeros(K)
        self.w     = np.zeros(K)

    def solve(self, rho: float):
        c_new = np.maximum(0.0,
                           self.w - (self.pi + self.mu) / (rho + 1e-8))
        c_new = np.minimum(c_new, self.c_max)
        total = c_new.sum()
        if total > self.C_max and total > 0:
            c_new *= self.C_max / total
        self.c = c_new


# ══════════════════════════════════════════════════════════════════════════════
#  4.  CONSENSUS AGENT
# ══════════════════════════════════════════════════════════════════════════════

def _proj_simplex(v: np.ndarray) -> np.ndarray:
    """Project v onto {x : Σx_i=1, x_i≥0}  (Duchi et al. 2008)."""
    n  = len(v)
    u  = np.sort(v)[::-1]
    cs = np.cumsum(u)
    rh = np.where(u > (cs - 1.0) / (np.arange(n) + 1.0))[0]
    if not len(rh):
        return np.ones(n) / n
    theta = (cs[rh[-1]] - 1.0) / (rh[-1] + 1.0)
    return np.maximum(v - theta, 0.0)


class ConsensusAgent:
    """
    Central consensus + dual update  (Sections VII–VIII of formulation).

    Manages:
      Z (K×R) — global assignment copies, simplex-feasible per request
      W (K×N) — global charging copies, capacity-feasible per station
      Λ (K×R) — dual variables for assignment
      M (K×N) — dual variables for charging

    Uses sparse W representation (only tracks non-zero stations) for memory
    efficiency with 602 stations × 10 vehicles.
    """

    def __init__(self, data: DataLoader, vehicles: list, stations: list):
        self.data     = data
        self.vehicles = vehicles
        self.stations = stations
        K, R, N       = data.n_veh, data.n_req, data.N

        self.Z   = np.full((K, R), 1.0 / K)
        self.W   = np.zeros((K, N))
        self.LAM = np.zeros((K, R))
        self.MU  = np.zeros((K, N))

        self.residuals = []
        self.primal_y  = []
        self.primal_c  = []
        self.dual_res  = []

    # ── Main update ───────────────────────────────────────────────────────
    def update(self, rho: float) -> float:
        """
        Full consensus + dual update.
        Returns r_prim = ‖Y−Z‖_F + ‖C−W‖_F.
        """
        K, R, N = self.data.n_veh, self.data.n_req, self.data.N

        Y = np.vstack([v.y for v in self.vehicles])    # (K,R)
        C = np.vstack([v.c for v in self.vehicles])    # (K,N)

        Z_old = self.Z.copy()
        W_old = self.W.copy()

        # Assignment consensus: simplex projection per request (Section VII)
        Z_new = np.zeros((K, R))
        for r in range(R):
            Z_new[:, r] = _proj_simplex(Y[:, r] + self.LAM[:, r] / rho)

        # Charging consensus: box projection per station (Section VII)
        # Only process stations with non-zero C or W to save time
        W_new  = np.zeros((K, N))
        active = np.where((C.sum(0) + self.W.sum(0)) > 0)[0]
        for s in active:
            tilde = C[:, s] + self.MU[:, s] / rho
            w_col = np.maximum(0.0, tilde)
            w_col = np.minimum(w_col, self.data.c_max)
            tot   = w_col.sum()
            if tot > self.data.C_max_s[s] and tot > 0:
                w_col *= self.data.C_max_s[s] / tot
            W_new[:, s] = w_col

        # Dual updates (Section VIII)
        LAM_new = self.LAM + rho * (Y - Z_new)
        MU_new  = self.MU  + rho * (C - W_new)

        # Residuals (Section IX)
        res_y  = np.linalg.norm(Y - Z_new)
        res_c  = np.linalg.norm(C - W_new)
        r_prim = res_y + res_c
        r_dual = rho * (np.linalg.norm(Z_new - Z_old)
                        + np.linalg.norm(W_new - W_old))

        self.primal_y.append(float(res_y))
        self.primal_c.append(float(res_c))
        self.residuals.append(float(r_prim))
        self.dual_res.append(float(r_dual))

        # Commit
        self.Z   = Z_new;   self.W   = W_new
        self.LAM = LAM_new; self.MU  = MU_new

        # Broadcast to vehicle agents
        for k, veh in enumerate(self.vehicles):
            veh.z   = self.Z[k, :]
            veh.w   = self.W[k, :]
            veh.lam = self.LAM[k, :]
            veh.mu  = self.MU[k, :]

        # Broadcast to station agents
        for s, sta in enumerate(self.stations):
            sta.w  = self.W[:, s]
            sta.mu = self.MU[:, s]

        return float(r_prim)

    # ── Final binary extraction (M1) ─────────────────────────────────────
    def extract_assignments(self) -> dict:
        """
        Argmax rounding with capacity-load penalty (M1 + M7).
        Most-certain requests assigned first; load penalty prevents
        all requests going to one vehicle.
        """
        K, R  = self.data.n_veh, self.data.n_req
        R_cap = int(np.ceil(R / K)) + 2
        load  = np.zeros(K, dtype=int)
        assign= {}
        for r in np.argsort(-self.Z.max(axis=0)):
            pen    = 0.10 * np.maximum(load - R_cap + 1, 0)
            k      = int(np.argmax(self.Z[:, r] - pen))
            assign[r] = k
            load[k]  += 1
        return assign


# ══════════════════════════════════════════════════════════════════════════════
#  5.  ADMM SOLVER
# ══════════════════════════════════════════════════════════════════════════════

class ADMMSolver:
    """
    Orchestrates the ADMM algorithm  (Section IX of formulation).

    Loop:
      Step 2: Vehicle subproblems (y update → route → c_feas → c update)
      Step 3: Station subproblems (c_s update)
      Step 4: Consensus (Z, W projections)
      Step 5: Dual update (Λ, M)
      Step 6: Residual check

    Adaptive ρ (M8): every 10 iterations, rescale ρ by 1.5
    if r_prim/r_dual imbalance > 10×.
    """

    def __init__(self, data: DataLoader,
                 rho: float     = 2.0,
                 max_iter: int  = 400,
                 tol: float     = 1e-2):
        self.data     = data
        self.rho      = rho
        self.max_iter = max_iter
        self.tol      = tol

        # Initialise agents  (Step 1: z=w=λ=μ=0)
        self.vehicles  = [VehicleAgent(k, data) for k in range(data.n_veh)]
        self.stations  = [ChargingStationAgent(s, data)
                          for s in range(data.n_stat)]
        self.consensus = ConsensusAgent(data, self.vehicles, self.stations)
        self.iter_log  = []

    # ── Main solve ────────────────────────────────────────────────────────
    def solve(self) -> dict:
        W = 72
        print(f"\n{'═'*W}")
        print("  ADMM IoEV — Joint Routing & Wireless Charging")
        print(f"{'═'*W}")
        print(f"  ρ={self.rho}  max_iter={self.max_iter}  ε={self.tol}")
        print(f"  K={self.data.n_veh}  R={self.data.n_req}  "
              f"S={self.data.n_stat}")
        print(f"{'─'*W}")
        print(f"  {'Iter':>5}  {'‖r_prim‖':>12}  {'‖y−z‖':>9}  "
              f"{'‖c−w‖':>10}  {'ρ':>6}  {'Obj':>12}")
        print(f"{'─'*W}")

        t0 = time.time()

        for it in range(1, self.max_iter + 1):

            # Step 2: Vehicle subproblems
            for veh in self.vehicles:
                veh.solve(self.rho)

            # Step 3: Station subproblems
            for sta in self.stations:
                sta.solve(self.rho)

            # Steps 4+5: Consensus + Dual
            r_prim = self.consensus.update(self.rho)

            # Step 6: adaptive ρ (M8) every 10 iters
            if it % 10 == 0 and self.consensus.dual_res:
                r_dual = self.consensus.dual_res[-1]
                if r_prim > 10 * (r_dual + 1e-12):
                    self.rho = min(self.rho * 1.5, 100.0)
                elif r_dual > 10 * (r_prim + 1e-12):
                    self.rho = max(self.rho / 1.5, 0.1)

            obj   = self._objective()
            res_y = self.consensus.primal_y[-1]
            res_c = self.consensus.primal_c[-1]
            self.iter_log.append({
                'iter':it, 'residual':r_prim,
                'res_y':res_y, 'res_c':res_c,
                'obj':obj,     'rho':self.rho
            })

            if it <= 5 or it % 20 == 0 or r_prim < self.tol:
                print(f"  {it:>5}  {r_prim:>12.6f}  {res_y:>9.6f}  "
                      f"{res_c:>10.6f}  {self.rho:>6.2f}  {obj:>12.4f}")

            if r_prim < self.tol and it >= 10:
                print(f"\n  ✓ Converged  iter={it}  ‖r‖={r_prim:.7f}")
                break

        print(f"{'─'*W}")
        print(f"  Elapsed={time.time()-t0:.2f}s  "
              f"ρ_final={self.rho:.3f}  "
              f"‖r‖_final={self.consensus.residuals[-1]:.7f}")

        return self._extract()

    # ── Objective ─────────────────────────────────────────────────────────
    def _objective(self) -> float:
        return sum(v.route_cost() + v.charging_cost() for v in self.vehicles)

    # ── Extract final integer-feasible solution ───────────────────────────
    def _extract(self) -> dict:
        """
        1. Binary-round y via argmax (M1).
        2. Discretise c to {0,5,15,20} kWh (M5, applied here not during ADMM).
        3. Rebuild routes + SOC with hard binary assignment.
        """
        assign    = self.consensus.extract_assignments()
        k2r       = {k: [] for k in range(self.data.n_veh)}
        for r in assign.keys():
            k = assign[r]
            k2r[k].append(r)

        levels = self.data.charge_levels
        for k, veh in enumerate(self.vehicles):
            # Hard binary y
            y_bin = np.zeros(self.data.n_req)
            for r in k2r[k]:
                y_bin[r] = 1.0
            veh.y = y_bin

            # Discretise c (M5)
            veh.c = levels[np.argmin(
                np.abs(veh.c[:, None] - levels[None, :]), axis=1
            )].astype(float)

            # Rebuild route with hard assignment + discretised c
            route = veh._build_greedy_route()
            veh._simulate_soc(route)

        return {
            'assignments'   : assign,
            'k_to_requests' : k2r,
            'routes'        : {k: v.route         for k,v in enumerate(self.vehicles)},
            'soc_profiles'  : {k: v.soc_profile   for k,v in enumerate(self.vehicles)},
            'charge_events' : {k: v.charge_events  for k,v in enumerate(self.vehicles)},
            'final_soc'     : {k: v.final_soc()   for k,v in enumerate(self.vehicles)},
            'min_soc'       : {k: v.min_soc()     for k,v in enumerate(self.vehicles)},
            'route_costs'   : {k: v.route_cost()  for k,v in enumerate(self.vehicles)},
            'charging_costs': {k: v.charging_cost() for k,v in enumerate(self.vehicles)},
            'total_obj'     : self._objective(),
            'residuals'     : self.consensus.residuals,
            'primal_y'      : self.consensus.primal_y,
            'primal_c'      : self.consensus.primal_c,
            'dual_res'      : self.consensus.dual_res,
            'iter_log'      : self.iter_log,
            'n_iters'       : len(self.iter_log),
        }


# ══════════════════════════════════════════════════════════════════════════════
#  6.  PRINT RESULTS
# ══════════════════════════════════════════════════════════════════════════════

def print_results(sol: dict, data: DataLoader):
    W = 72
    print(f"\n{'═'*W}\n  FINAL SOLUTION REPORT\n{'═'*W}")

    # ── Request assignments ───────────────────────────────────────────────
    print("\n  REQUEST ASSIGNMENTS")
    print(f"  {'Req':>4}  {'Vehicle':>8}  {'Pickup':>7}  "
          f"{'Delivery':>9}  {'Pri':>4}  {'Energy(kWh)':>11}")
    print("  " + "─"*60)
    for r in range(data.n_req):
        k = sol['assignments'][r]
        print(f"  {r+1:>4}  veh_{k+1:<3}     "
              f"{data.req_pickup[r]:>7}  "
              f"{data.req_delivery[r]:>9}  "
              f"{int(data.req_priority[r]):>4}  "
              f"{data.trip_energy[r]:>11.3f}")

    # ── Vehicle performance ───────────────────────────────────────────────
    print("\n  VEHICLE PERFORMANCE")
    print(f"  {'Veh':>4}  {'#Req':>5}  {'Route(km)':>10}  "
          f"{'ChgCost($)':>11}  {'SOC_min':>8}  {'SOC_fin':>8}  "
          f"{'#ChgEvt':>7}")
    print("  " + "─"*66)
    for k in range(data.n_veh):
        print(f"  v{k+1:<3}  {len(sol['k_to_requests'][k]):>5}  "
              f"{sol['route_costs'][k]:>10.3f}  "
              f"{sol['charging_costs'][k]:>11.5f}  "
              f"{sol['min_soc'][k]:>8.3f}  "
              f"{sol['final_soc'][k]:>8.3f}  "
              f"{len(sol['charge_events'][k]):>7}")

    # ── Charging schedule ─────────────────────────────────────────────────
    print("\n  CHARGING SCHEDULE")
    print(f"  {'Veh':>4}  {'Node':>6}  {'kWh':>6}  "
          f"{'Price($/kWh)':>13}  {'SOC_before':>10}  {'SOC_after':>9}")
    print("  " + "─"*60)
    any_c = False
    for k in range(data.n_veh):
        for node, amt, sb, sa in sol['charge_events'][k]:
            print(f"  v{k+1:<3}  {node:>6}  {amt:>6.2f}  "
                  f"{data.node_price[node]:>13.4f}  "
                  f"{sb:>10.3f}  {sa:>9.3f}")
            any_c = True
    if not any_c:
        print("  (No charging events triggered)")

    # ── SOC profiles ─────────────────────────────────────────────────────
    print("\n  BATTERY SOC PROFILE (kWh)")
    print(f"  {'Veh':>4}  {'Init':>6}  {'Min':>8}  {'Final':>8}  {'Nodes':>6}")
    print("  " + "─"*42)
    for k in range(data.n_veh):
        p = sol['soc_profiles'][k]
        print(f"  v{k+1:<3}  {p[0]:>6.2f}  "
              f"{min(p):>8.3f}  {p[-1]:>8.3f}  {len(p):>6}")

    # ── Objective ─────────────────────────────────────────────────────────
    tot_r = sum(sol['route_costs'].values())
    tot_c = sum(sol['charging_costs'].values())
    print(f"\n  OBJECTIVE")
    print(f"  Routing cost   : {tot_r:>10.4f} km")
    print(f"  Charging cost  : {tot_c:>10.6f} ڈالر")
    print(f"  Combined       : {sol['total_obj']:>10.4f}")
    print(f"  Iterations     : {sol['n_iters']}")
    print(f"  Final residual : {sol['residuals'][-1]:.7f}")
    print(f"{'═'*W}")


# ══════════════════════════════════════════════════════════════════════════════
#  7.  PLOTS  (4 research-quality figures)
# ══════════════════════════════════════════════════════════════════════════════

BG = 'white'

def _ax(ax):
    ax.set_facecolor(BG)

    # Change tick labels to black
    ax.tick_params(colors='black', labelsize=9)

    # Change axis spines (borders) to black
    for sp in ax.spines.values():
        sp.set_edgecolor('black')

    # Optional: make grid lighter or disable it if needed
    ax.grid(True, color='black', lw=0.5, alpha=0.2)

    # Ensure axis labels are black
    ax.xaxis.label.set_color('black')
    ax.yaxis.label.set_color('black')


# ── Plot 1: Vehicle Routes ────────────────────────────────────────────────────
def plot_routes(sol, data, out):
    fig, ax = plt.subplots(figsize=(13, 12))
    fig.patch.set_facecolor(BG)
    _ax(ax)
    xy = data.xy

    # Background pickup / delivery nodes
    pn_df = data.nodes[data.nodes['node_type'] == 'pickup']
    dn_df = data.nodes[data.nodes['node_type'] == 'delivery']
    ax.scatter(pn_df['x_km'], pn_df['y_km'],
               c='#4FC3F7', s=16, alpha=0.18, zorder=1)
    ax.scatter(dn_df['x_km'], dn_df['y_km'],
               c='#F48FB1', s=16, alpha=0.18, zorder=1)

    # OD grey arcs
    for r in range(data.n_req):
        p = data.req_pickup[r]; d = data.req_delivery[r]
        ax.plot([xy[p,0], xy[d,0]], [xy[p,1], xy[d,1]],
                color='#1E1E30', lw=0.5, alpha=0.6, zorder=2)

    # Depot star
    ax.scatter([xy[data.start,0]], [xy[data.start,1]],
               c='#FFE066', s=400, marker='*', zorder=9,
               edgecolors='#FFB300', lw=1.2)
    ax.annotate('DEPOT', (xy[data.start,0]+0.5, xy[data.start,1]+0.5),
                color='#FFE066', fontsize=9, fontweight='bold', zorder=10)

    legs = []
    for k in range(data.n_veh):
        route = sol['routes'][k]
        if len(route) <= 2:
            continue
        col = VEH_COLORS[k]
        rxs = [xy[n,0] for n in route]
        rys = [xy[n,1] for n in route]
        ax.plot(rxs, rys, color=col, lw=2.2, alpha=0.88,
                zorder=4, solid_capstyle='round')

        # Direction arrow near midpoint
        mid = max(1, len(route)//2)
        if mid < len(rxs):
            dx = rxs[mid]-rxs[mid-1]; dy = rys[mid]-rys[mid-1]
            if abs(dx)+abs(dy) > 0.2:
                ax.annotate('',
                    xy=(rxs[mid], rys[mid]),
                    xytext=(rxs[mid]-0.45*dx, rys[mid]-0.45*dy),
                    arrowprops=dict(arrowstyle='->', color=col, lw=1.8,
                                    mutation_scale=14), zorder=6)

        # Assigned pickups (circle) and deliveries (square)
        for r in sol['k_to_requests'][k]:
            pnode = data.req_pickup[r];   dnode = data.req_delivery[r]
            ax.scatter(xy[pnode,0], xy[pnode,1], color=col, s=65,
                       marker='o', zorder=7, edgecolors='white', lw=0.6)
            ax.scatter(xy[dnode,0], xy[dnode,1], color=col, s=60,
                       marker='s', zorder=7, edgecolors='white', lw=0.6)

        nr = len(sol['k_to_requests'][k])
        legs.append(mpatches.Patch(color=col, label=f'V{k+1} ({nr} req)'))

    # Charging events
    shown = False
    for k in range(data.n_veh):
        for node, amt, _, _ in sol['charge_events'][k]:
            lbl = '⚡ Charging event' if not shown else ''
            ax.scatter(xy[node,0], xy[node,1],
                       c='#76FF7A', s=180, marker='P', zorder=10,
                       edgecolors='white', lw=0.9, label=lbl)
            ax.annotate(f'{amt:.0f} kWh',
                        (xy[node,0], xy[node,1]),
                        xytext=(5, 5), textcoords='offset points',
                        color='#76FF7A', fontsize=7.5, fontweight='bold')
            shown = True

    extra = [
        mlines.Line2D([],[],color='#4FC3F7',marker='o',ls='',ms=7,
                      alpha=0.5, label='Pickup nodes'),
        mlines.Line2D([],[],color='#F48FB1',marker='s',ls='',ms=7,
                      alpha=0.5, label='Delivery nodes'),
        mlines.Line2D([],[],color='#FFE066',marker='*',ls='',ms=11,
                      label='Depot'),
    ]
    if shown:
        extra.append(mlines.Line2D([],[],color='#76FF7A',marker='P',
                                   ls='',ms=10, label='⚡ Charging'))

    ax.legend(handles=legs+extra, loc='upper right', ncol=4,
              fontsize=7.8, facecolor='#1A1A2E', edgecolor='#333',
              labelcolor='white', framealpha=0.93)
    ax.set_xlim(-1,63); ax.set_ylim(-1,63)
    ax.set_xlabel('x (km)', color='#AAAAAA', fontsize=11)
    ax.set_ylabel('y (km)', color='#AAAAAA', fontsize=11)
    ax.set_title('IoEV Vehicle Routes  ·  100 Requests · 10 Vehicles · 60×60 km²',
                 color='white', fontsize=13, fontweight='bold', pad=12)
    fp = os.path.join(out, 'plot1_vehicle_routes.png')
    plt.tight_layout()
    plt.savefig(fp, dpi=160, bbox_inches='tight', facecolor=BG)
    plt.close()
    return fp


# ── Plot 2: SOC Curves ────────────────────────────────────────────────────────
def plot_soc(sol, data, out):
    fig, ax = plt.subplots(figsize=(14, 6))
    fig.patch.set_facecolor(BG)
    _ax(ax)

    for k in range(data.n_veh):
        p   = sol['soc_profiles'][k]
        xs  = np.linspace(0, 100, len(p))
        col = VEH_COLORS[k]
        ax.plot(xs, p, color=col, lw=2.3, alpha=0.88, label=f'V{k+1}')
        ax.fill_between(xs, p, alpha=0.05, color=col)

        # Annotate each charging event
        route = sol['routes'][k]
        for node, amt, sb, sa in sol['charge_events'][k]:
            if node in route:
                idx  = route.index(node)
                xpos = idx / max(len(route)-1,1) * 100
                ax.annotate(f'⚡{amt:.0f}',
                            xy=(xpos, sb), xytext=(xpos+1.5, sb+1.8),
                            color='#76FF7A', fontsize=9, fontweight='bold',
                            arrowprops=dict(arrowstyle='->', color='#76FF7A', lw=0.9))

    ax.axhline(data.B_min, color='#FF5252', ls='--', lw=1.7, alpha=0.9,
               label=f'B_min = {data.B_min:.0f} kWh (10%)')
    ax.axhline(data.B_thr, color='#FF9800', ls=':',  lw=1.4, alpha=0.85,
               label=f'Charge trigger = {data.B_thr:.0f} kWh (35%)')
    ax.axhline(data.B_max, color='#42A5F5', ls='--', lw=1.7, alpha=0.8,
               label=f'B_max = {data.B_max:.0f} kWh')

    ax.set_ylim(0, data.B_max*1.15)
    ax.set_xlabel('Route Progress (%)', color='#AAAAAA', fontsize=11)
    ax.set_ylabel('Battery SOC (kWh)', color='#AAAAAA', fontsize=11)
    ax.set_title('Battery State-of-Charge Profiles Along Routes',
                 color='white', fontsize=13, fontweight='bold', pad=10)
    ax.legend(fontsize=8.5, ncol=5, loc='upper right',
              facecolor='#1A1A2E', edgecolor='#333', labelcolor='white')
    fp = os.path.join(out, 'plot2_soc_curves.png')
    plt.tight_layout()
    plt.savefig(fp, dpi=160, bbox_inches='tight', facecolor=BG)
    plt.close()
    return fp


# ── Plot 3: Charging Schedule ─────────────────────────────────────────────────
def plot_charging(sol, data, out):
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    fig.patch.set_facecolor(BG)
    for ax in axes:
        _ax(ax)

    labels = [f'V{k+1}' for k in range(data.n_veh)]
    kwh    = [sum(a for _,a,_,_ in sol['charge_events'][k])
              for k in range(data.n_veh)]
    n_ev   = [len(sol['charge_events'][k]) for k in range(data.n_veh)]
    cost   = [sol['charging_costs'][k] for k in range(data.n_veh)]
    cols   = VEH_COLORS

    specs  = [
        (axes[0], kwh,  'Total kWh Charged',      'kWh',       '{:.1f}'),
        (axes[1], n_ev, 'Number of Charge Events', 'Events',    '{:d}'),
        (axes[2], cost, 'Charging Cost ($)',        'Cost ($)',  '${:.4f}'),
    ]
    for ax, vals, title, ylabel, fmt in specs:
        bars = ax.bar(labels, vals, color=cols,
                      edgecolor='#111', lw=0.7, alpha=0.93)
        max_v = max(vals) if max(vals) > 0 else 1
        for b, v in zip(bars, vals):
            if v > 0:
                txt = (fmt.format(int(v)) if '{:d}' in fmt
                       else fmt.format(v))
                ax.text(b.get_x()+b.get_width()/2,
                        b.get_height()+0.02*max_v,
                        txt, ha='center', color='white',
                        fontsize=9.5, fontweight='bold')
        ax.set_title(title, color='white', fontsize=12,
                     fontweight='bold', pad=8)
        ax.set_xlabel('Vehicle', color='#AAAAAA', fontsize=10)
        ax.set_ylabel(ylabel, color='#AAAAAA', fontsize=10)
        if 'Events' in ylabel:
            ax.yaxis.set_major_locator(plt.MaxNLocator(integer=True))

    tot = sum(cost)
    fig.suptitle(f'Wireless Charging Schedule  ·  Total Cost = ${tot:.5f}',
                 color='white', fontsize=14, fontweight='bold', y=1.02)
    fp = os.path.join(out, 'plot3_charging_schedule.png')
    plt.tight_layout()
    plt.savefig(fp, dpi=160, bbox_inches='tight', facecolor=BG)
    plt.close()
    return fp


# ── Plot 4: ADMM Convergence ──────────────────────────────────────────────────
def plot_convergence(sol, out):
    iters = [r['iter']    for r in sol['iter_log']]
    res   = [r['residual']for r in sol['iter_log']]
    res_y = [r['res_y']   for r in sol['iter_log']]
    res_c = [r['res_c']   for r in sol['iter_log']]
    objs  = [r['obj']     for r in sol['iter_log']]
    rhos  = [r['rho']     for r in sol['iter_log']]
    dres  = sol.get('dual_res', [])

    fig = plt.figure(figsize=(18, 10))
    fig.patch.set_facecolor(BG)
    gs  = gridspec.GridSpec(2, 3, hspace=0.42, wspace=0.35,
                            left=0.07, right=0.97, top=0.92, bottom=0.08)
    ax1 = fig.add_subplot(gs[0,:2])
    ax2 = fig.add_subplot(gs[0,2])
    ax3 = fig.add_subplot(gs[1,:2])
    ax4 = fig.add_subplot(gs[1,2])
    for ax in [ax1,ax2,ax3,ax4]:
        _ax(ax)

    # Primal residuals
    ax1.semilogy(iters, res,   color='#FFE066', lw=2.5,
                 label='Total  ‖y−z‖_F + ‖c−w‖_F')
    ax1.semilogy(iters, res_y, color='#42A5F5', lw=1.7,
                 ls='--', alpha=0.9, label='‖y−z‖_F  (assignment)')
    ax1.semilogy(iters, res_c, color='#FF7043', lw=1.7,
                 ls='--', alpha=0.9, label='‖c−w‖_F  (charging)')
    ax1.axhline(1e-2, color='#FF5252', ls=':', lw=1.6,
                label=f'ε = 0.01')
    ax1.set_title('ADMM Primal Residuals  (log scale)',
                  color='white', fontsize=12, fontweight='bold', pad=8)
    ax1.set_xlabel('Iteration', color='#AAAAAA', fontsize=10)
    ax1.set_ylabel('‖r_prim‖', color='#AAAAAA', fontsize=10)
    ax1.legend(fontsize=9, facecolor='#1A1A2E',
               edgecolor='#333', labelcolor='white')

    # Adaptive ρ
    ax2.step(iters, rhos, color='#AB47BC', lw=2.0, where='post')
    ax2.set_title('Adaptive ρ  (M8)', color='white', fontsize=12,
                  fontweight='bold', pad=8)
    ax2.set_xlabel('Iteration', color='#AAAAAA', fontsize=10)
    ax2.set_ylabel('ρ', color='#AAAAAA', fontsize=10)

    # Objective
    ax3.plot(iters, objs, color='#66BB6A', lw=2.4)
    ax3.fill_between(iters, objs, min(objs)*0.97, alpha=0.10, color='#66BB6A')
    ax3.annotate(f'Final: {objs[-1]:.2f}',
                 xy=(iters[-1], objs[-1]),
                 xytext=(iters[-1]*0.70, objs[-1]*1.04),
                 color='#66BB6A', fontsize=9,
                 arrowprops=dict(arrowstyle='->', color='#66BB6A', lw=1.0))
    ax3.set_title('Objective Value  (routing km + charging $)',
                  color='white', fontsize=12, fontweight='bold', pad=8)
    ax3.set_xlabel('Iteration', color='#AAAAAA', fontsize=10)
    ax3.set_ylabel('Objective', color='#AAAAAA', fontsize=10)

    # Dual residual
    if dres:
        ax4.semilogy(iters[:len(dres)], dres, color='#EF5350', lw=1.9,
                     label='Dual ‖r_dual‖')
        ax4.set_title('Dual Residual  (log scale)',
                      color='white', fontsize=12, fontweight='bold', pad=8)
        ax4.set_xlabel('Iteration', color='#AAAAAA', fontsize=10)
        ax4.set_ylabel('‖r_dual‖', color='#AAAAAA', fontsize=10)
        ax4.legend(fontsize=9, facecolor='#1A1A2E',
                   edgecolor='#333', labelcolor='white')

    fig.suptitle(
        'ADMM Convergence Diagnostics  ·  '
        'Feasibility-First Charging  ·  Adaptive ρ  ·  Continuous c',
        color='white', fontsize=13, fontweight='bold', y=0.975)
    fp = os.path.join(out, 'plot4_admm_convergence.png')
    plt.savefig(fp, dpi=160, bbox_inches='tight', facecolor=BG)
    plt.close()
    return fp


# ══════════════════════════════════════════════════════════════════════════════
#  8.  MAIN
# ══════════════════════════════════════════════════════════════════════════════

def main():
    print("\n" + "═"*72)
    print("  IoEV ADMM  —  Joint Routing & Wireless Charging")
    print("  Formulation: Final_formulation.docx")
    print("  Dataset: paper-matched 100-request synthetic instance")
    print("═"*72)

    data   = DataLoader("requests_100.csv")
    solver = ADMMSolver(data, rho=2.0, max_iter=150, tol=1e-2)
    sol    = solver.solve()

    print_results(sol, data)

    print("\n  Generating plots ...")
    p1 = plot_routes(sol, data, OUT_DIR)
    p2 = plot_soc(sol, data, OUT_DIR)
    p3 = plot_charging(sol, data, OUT_DIR)
    p4 = plot_convergence(sol, OUT_DIR)
    for p in [p1,p2,p3,p4]:
        print(f"  ✓ {p}")

    # JSON summary
    summary = {
        'formulation':       'Final_formulation.docx — ADMM Sections I–IX',
        'modifications':     ['M1–M9 (see docstring)'],
        'charging_fix':      'c=max(c_feas,c_price) [Eq.C M4]; '
                             'continuous c during ADMM [M5]',
        'total_objective':   round(sol['total_obj'],4),
        'routing_cost_km':   round(sum(sol['route_costs'].values()),4),
        'charging_cost_usd': round(sum(sol['charging_costs'].values()),6),
        'n_iterations':      sol['n_iters'],
        'final_residual':    round(sol['residuals'][-1],8),
        'assignments': {f'req_{r+1}': f'veh_{k+1}'
                        for r,k in sol['assignments'].items()},
        'requests_per_vehicle': {f'veh_{k+1}': len(sol['k_to_requests'][k])
                                  for k in range(data.n_veh)},
        'route_costs_km': {f'veh_{k+1}': round(sol['route_costs'][k],3)
                            for k in range(data.n_veh)},
        'charging_costs': {f'veh_{k+1}': round(sol['charging_costs'][k],5)
                            for k in range(data.n_veh)},
        'final_soc_kWh':  {f'veh_{k+1}': round(sol['final_soc'][k],3)
                            for k in range(data.n_veh)},
        'charge_events': {f'veh_{k+1}':
                          [(n, round(a,2), round(sb,3), round(sa,3))
                           for n,a,sb,sa in sol['charge_events'][k]]
                          for k in range(data.n_veh)},
    }
    jp = os.path.join(OUT_DIR, 'solution_summary.json')
    with open(jp,'w') as f:
        json.dump(summary, f, indent=2)
    print(f"  ✓ {jp}")
    return sol, data


if __name__ == '__main__':
    sol, data = main()





